# Menggunakan image Python resmi
FROM python:3.10-slim

# Menentukan direktori kerja di dalam container
WORKDIR /coba

# Menyalin file app.py ke dalam container
COPY hello.py .

# Perintah yang dijalankan saat container dijalankan
CMD ["python", "hello.py"]